# Generated by Django 4.1.7 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_device', models.CharField(max_length=30)),
                ('mac_address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=30)),
                ('switch_name', models.CharField(max_length=9, null=True)),
                ('switch_port', models.CharField(default='unknown', max_length=2, null=True)),
                ('ip', models.CharField(max_length=16)),
                ('imbis', models.CharField(choices=[('T', 'Jest w Imbisie'), ('N', 'Nie ma w imbisie')], max_length=1)),
                ('edit_date', models.DateField()),
            ],
        ),
    ]
