# Generated by Django 4.1.7 on 2023-05-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_type_of_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Urządzenie', 'verbose_name_plural': 'Urządzenia'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='IP',
        ),
    ]
