# Generated by Django 4.1.7 on 2023-05-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_options_rename_ip_device_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='IP',
            new_name='iP',
        ),
    ]
