# Generated by Django 4.1.7 on 2023-05-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_ip_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=9, null=True)),
                ('switch_port', models.CharField(default='unknown', max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='switch_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='switch_port',
        ),
        migrations.AddField(
            model_name='device',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.switches'),
        ),
    ]
