# Generated by Django 4.1.7 on 2023-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_switches_remove_device_switch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switches',
            name='switch_port',
        ),
        migrations.AddField(
            model_name='device',
            name='switch_port',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
