# Generated by Django 4.1.7 on 2023-05-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_switches_switch_ip_switches_switch_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switches',
            old_name='switch_IP',
            new_name='switch_ip',
        ),
    ]
