# Generated by Django 4.1.7 on 2023-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_rename_switch_ip_switches_switch_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type_of_device',
            field=models.CharField(choices=[('Access Point', 'AP'), ('Desktop', 'D'), ('Notebook', 'N'), ('Etykieciarka', 'E'), ('Zebra', 'Z'), ('Telewizor', 'TV'), ('Printer', 'P')], max_length=30),
        ),
    ]
