# Generated by Django 4.1.7 on 2023-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_type_of_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type_of_device',
            field=models.CharField(choices=[('Access Point', 'AP'), ('Desktop', 'D'), ('Notebook', 'N'), ('Etykieciarka', 'E'), ('Zebra', 'Z'), ('Telewizor', 'TV'), ('Printer', 'P')], max_length=30),
        ),
    ]
