# Generated by Django 4.1.7 on 2023-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_switches_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type_of_device',
            field=models.CharField(choices=[('Access Point', 'Access Point'), ('Desktop', 'Desktop'), ('Notebook', 'Notebook'), ('Etykieciarka', 'E'), ('Zebra', 'Z'), ('Telewizor', 'TV'), ('Printer', 'P')], max_length=30),
        ),
    ]
