# Generated by Django 4.1.7 on 2023-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_device_type_of_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='1', max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Typ Urządzeń',
                'verbose_name_plural': 'Typy Urządzeń',
            },
        ),
        migrations.AlterField(
            model_name='switches',
            name='switch_ip',
            field=models.CharField(default='1', max_length=16),
        ),
    ]
