# Generated by Django 4.1.7 on 2023-06-02 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_devicetype_alter_switches_switch_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
        ),
    ]
