# Generated by Django 4.1.7 on 2023-06-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type_of_device',
        ),
    ]
