# Generated by Django 4.1.7 on 2023-06-02 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_remove_device_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='edit_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
